### ISSUE TITLE
Add GitHub action for build Android

### ISSUE THREAD

**Issue by georgeherby** [georgeherby/pass_the_pigs#7]
https://github.com/marketplace/actions/flutter-action

```
steps:
- uses: actions/checkout@v3
- uses: actions/setup-java@v2
  with:
    distribution: 'zulu'
    java-version: '11'
- uses: subosito/flutter-action@v2
  with:
    flutter-version: '2.10.4'
- run: flutter pub get
- run: flutter test
- run: flutter build apk
- run: flutter build appbundle
```
